name = "WarcraftGridGraphs"
uuid = "99715485-436c-46de-9958-b116d5ee026b"
authors = ["Guillaume Dalle"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1"
SimpleWeightedGraphs = "1.4"
SparseArrays = "1"
julia = "1.10"
